spring:
  application:
    name: GeoFreight
  profiles:
    active: prod

viacep:
  url:
    "https://viacep.com.br/ws"

melhor-envio:
  url:
    "https://melhorenvio.com.br"

validation-message:
  required-field:
    "O campo é obrigatório e não pode ser nulo ou vazio."

  invalid-cep:
    "O CEP deve conter pelo menos 8 caracteres."

  min-number:
    "O valor deve ser maior que 0."