spring:
  application:
    name: GeoFreight
  profiles:
    active: prod

viacep:
  url:
    "https://viacep.com.br/ws"

melhor-envio:
  url:
    "https://melhorenvio.com.br"

required:
  field:
    " é obrigatório e não pode ser nulo ou vazio"